### ISSUE TITLE
Is this the right behaviour?

### ISSUE THREAD

**Issue by infojunkie** [gritzko/todomvc-swarm#24]
I've tried the following experiment with the demo and would appreciate your feedback on the behaviour I've seen:
1. with Internet connectivity, open 2 different browsers, A and B
2. in A open http://ppyr.us and type "hello"+ENTER as first item
3. copy URL and paste it in browser B  
   => B shows "hello"
4. disable Internet connectivity
5. in A type "item 2"+ENTER as second item  
   => app says "3 items left"
6. in B type "item 3"+ENTER as second item  
   => app says "3 items left"
7. enable Internet connectivity and watch A for a few seconds  
   => "item 2" is replaced with "item 3", an extra blank item is added, and app says "4 items left"  
   => same for browser B

I haven't looked at the code yet, so I don't know if this is caused by the app logic or the underlying Swarm library.

**Comment by vmakhaev** [comment]
Looks similar to https://github.com/vmakhaev/todomvc-swarm/blob/546b09a4514af9fd5e6f856a3313357e4453c3d1/TodoRouter.js#L35
So it's probably not Level Storage issue

**Comment by infojunkie** [comment]
I checked the console: no message like "RACE! List length:"

**Comment by infojunkie** [comment]
I see your code link points to a fork of the codebase used in the demo. Are you saying that the additional code would solve this?

**Comment by gritzko** [comment]
Thanks a lot.
That is definitely a bug in Vector.js. Most likely an algorithm bug.
I can deal with it once I am back at my desk (tomorrow).

On 1 November 2014 12:11, Karim Ratib notifications@github.com wrote:

> I checked the console: no message like "RACE! List length:"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gritzko/todomvc-swarm/issues/24#issuecomment-61361315
> .

## 

Victor

**Comment by gritzko** [comment]
After 2 weeks, I finally reached to my keyboard to fix this bug.
Suddenly, I understood that it is the expected behavior, actually.
When you press ENTER for the 1st time, you create a line (empty).
Then you set _that_ line to "item 2" and "item 3" in respective disconnected replicas.

Text fields are LWW (last-write-wins) here. On reconnection, the latter edit overwrites the former one.

TodoList is a Vector implementing Causal Trees merge algorithm. When you press ENTER in disconnected mode, you create two _different_ empty lines. On reconnection, both lines appear at both replicas (vectors get merged).

So, there is no bug, unfortunately.
I see two possibilities to straighten the UX:
1) Pressing ENTER after the last line is sort of a bad practice here, cause users will naturally start writing new entries in the empty line, which has an identity, so there is a semantic conflict, of sorts. We may discourage this behavior (warning etc).
2) We may use Text for TodoItem's content. That way, item content will also get merged (not LWW'd). That will create some ugly cases, like "item 2item 3" entry, but at least nothing gets lost.

Thoughts?

**Comment by infojunkie** [comment]
Thanks for your reply. 

Disclaimer: I haven't tried to dig into the code of Swarm.js, and I hope I don't have to just yet, so please bear with me as a "client" of the library - someone who is coding the todomvc-swarm app for example.

The main use-case I imagine for a collaborative, offline-ready TODO app is to allow users to collaborate on a list by adding items whether they are online or offline. When sync happens, items are either merged or appended.

The challenge is to specify the semantics of the above phrase "either merged or appended" in a coherent and feasible way. I think the discussion is happening at this level. 

You mentioned that the TodoList is implemented as a Vector, by which I assume (again without looking at the library code) that the _order_ of items matters. Hence, item 3 for browser A and item 3 for browser B are somehow related, by virtue of their position in the vector. However, for users of that app, the order might be less relevant than the mere _existence_ of an item in the list. Formally, we'd be talking about a set rather than a list. This certainly makes sense if user A and user B are offline, adding items to their respectives lists, and expect the app to sync by appending all items once reconnected.

TodoList implemented as a Set would, in the simplest case, just do the above. More complex cases would involve overwriting existing items (using LWW) and detecting duplicates - but I'll leave those to later discussions if we agree on the above.

I hope this makes sense to you!

**Comment by rocketraman** [comment]
@gritzko Wouldn't the right fix be to simply delay the UI event that creates the TODO item? Currently, "Enter" causes a new (blank) item to be created which is then simultaneously edited by A and B offline.

Instead, "Enter" should create a new (blank) item on the UI, but not yet associate that blank item to the swarm model. Only once the user starts typing text into a blank item would a new model item be created. In this way, when A and B are offline, they will both create separate Todo items in the ToDoList Vector.

**Comment by gritzko** [comment]
Indeed, the original TodoMVC works that way. The input is not an actual entry.
